
import static java.lang.Integer.parseInt;
import javax.swing.Icon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jhiej
 */
public class PenjualanMotor extends javax.swing.JFrame {

    /**
     * Creates new form PenjualanMotor
     */
    public PenjualanMotor() {
        initComponents();
        hargaMotor.setEnabled(false);
        diskonHarga.setEnabled(false);
        totalBayar.setEnabled(false);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        NamaPembeli = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PilihMerk = new javax.swing.JComboBox<>();
        motorBebek = new javax.swing.JRadioButton();
        motorMatic = new javax.swing.JRadioButton();
        motorSport = new javax.swing.JRadioButton();
        hargaMotor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenisPembayaran = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        diskonHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hitungHarga = new javax.swing.JButton();
        hitungLagi = new javax.swing.JButton();
        keluarApps = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nama Pembeli");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 29, -1, -1));

        NamaPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPembeliActionPerformed(evt);
            }
        });
        getContentPane().add(NamaPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 26, 182, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Merk Motor");

        jLabel3.setText("Jenis Motor");

        jLabel4.setText("Harga");

        PilihMerk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Jenis Motor----", "Honda", "Yamaha", "Suzuki", "Kawasaki" }));
        PilihMerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PilihMerkActionPerformed(evt);
            }
        });

        buttonGroup1.add(motorBebek);
        motorBebek.setText("Bebek");
        motorBebek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorBebekActionPerformed(evt);
            }
        });

        buttonGroup1.add(motorMatic);
        motorMatic.setText("Matic");
        motorMatic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorMaticActionPerformed(evt);
            }
        });

        buttonGroup1.add(motorSport);
        motorSport.setText("Sport");
        motorSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motorSportActionPerformed(evt);
            }
        });

        jLabel8.setText("Data Motor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(motorBebek)
                                .addGap(18, 18, 18)
                                .addComponent(motorMatic)
                                .addGap(28, 28, 28)
                                .addComponent(motorSport))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(PilihMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(hargaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PilihMerk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motorBebek)
                    .addComponent(motorMatic)
                    .addComponent(motorSport)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hargaMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 74, -1, -1));

        jLabel5.setText("Pembayaran");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 291, -1, -1));

        jenisPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----Pembayaran----", "Cash", "Kredit" }));
        jenisPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(jenisPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 288, 194, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        diskonHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diskonHargaActionPerformed(evt);
            }
        });

        jLabel6.setText("Diskon (%)");

        jLabel7.setText("Total Bayar");

        jLabel9.setText("Harga Motor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(diskonHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(totalBayar))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskonHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 388, -1, -1));

        hitungHarga.setText("Hitung");
        hitungHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungHargaActionPerformed(evt);
            }
        });
        getContentPane().add(hitungHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 287, -1, -1));

        hitungLagi.setText("Hitung Lagi");
        hitungLagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungLagiActionPerformed(evt);
            }
        });
        getContentPane().add(hitungLagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 525, -1, -1));

        keluarApps.setText("Selesai");
        keluarApps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarAppsActionPerformed(evt);
            }
        });
        getContentPane().add(keluarApps, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 525, -1, -1));

        jLabel10.setText("Nama : Jeremy Tumbur M.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 130, 20));

        jLabel11.setText("NIM : 200101072060");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, 10));

        jLabel12.setText("Kelas : SI-401");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPembeliActionPerformed

    private void motorBebekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorBebekActionPerformed
        String Val= PilihMerk.getSelectedItem().toString();
    
        if("Honda".equals(Val)){
             hargaMotor.setText(String.valueOf(12000000));
        }
        else if("Suzuki".equals(Val)){
            hargaMotor.setText(String.valueOf(14000000));
        }
        else if("Yamaha".equals(Val)){

            hargaMotor.setText(String.valueOf(13500000));
        }
         else if("Kawasaki".equals(Val)){
            hargaMotor.setText(String.valueOf(12500000));
        }else {
             JOptionPane.showMessageDialog(this, "Merk Motor Belum di pilih"); 
             hargaMotor.setText("");
        }
    }//GEN-LAST:event_motorBebekActionPerformed

    private void jenisPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisPembayaranActionPerformed

    }//GEN-LAST:event_jenisPembayaranActionPerformed

    private void diskonHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diskonHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diskonHargaActionPerformed

    private void PilihMerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PilihMerkActionPerformed

    }//GEN-LAST:event_PilihMerkActionPerformed

    private void motorMaticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorMaticActionPerformed
        String Val= PilihMerk.getSelectedItem().toString();
         
        if("Honda".equals(Val)){
            hargaMotor.setText(String.valueOf(15000000));
        }
        else if("Suzuki".equals(Val)){
              hargaMotor.setText(String.valueOf(13000000));
        }
        else if("Yamaha".equals(Val)){
            hargaMotor.setText(String.valueOf(14000000));
        }
         else if("Kawasaki".equals(Val)){
            hargaMotor.setText(String.valueOf(13500000));
        }else{
             JOptionPane.showMessageDialog(this, "Merk Motor Belum di pilih"); 
             hargaMotor.setText(String.valueOf(""));
        }
        
    }//GEN-LAST:event_motorMaticActionPerformed

    private void hitungHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungHargaActionPerformed
        String combo1 = PilihMerk.getSelectedItem().toString();
        String Val= jenisPembayaran.getSelectedItem().toString();
        String Radio1 = motorBebek.getText();
        String Radio2 = motorMatic.getText();
        String Radio3 = motorSport.getText();
        Integer TextField2, TextField3, diskon, result;
        if("Cash".equals(Val) ){
            if("Bebek".equals(Radio1)){
                if("Honda".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Suzuki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon; 
                    totalBayar.setText(String.valueOf(result));
                }else if("Yamaha".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Kawasaki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result)); 
                 }
            }
            else if("Matic".equals(Radio2)){
                 if("Honda".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Suzuki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Yamaha".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Kawasaki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }
            }
            else if("Sport".equals(Radio3)){
                 if("Honda".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Suzuki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Yamaha".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Kawasaki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(20));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }
            }
        }
        else if("Kredit".equals(Val)){
             if("Bebek".equals(Radio1)){
                if("Honda".equals(combo1)){
                    diskonHarga.setText(String.valueOf(8));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Suzuki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(7));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;;
                    totalBayar.setText(String.valueOf(result));
                }else if("Yamaha".equals(combo1)){
                    diskonHarga.setText(String.valueOf(6));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                    }else if("Kawasaki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(5));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }
        }
        else if("Matic".equals(Radio2)){
                if("Honda".equals(combo1)){
                    diskonHarga.setText(String.valueOf(8));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Suzuki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(7));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Yamaha".equals(combo1)){
                    diskonHarga.setText(String.valueOf(6));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Kawasaki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(5));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }
             }
        else if("Sport".equals(Radio1)){
                if("Honda".equals(combo1)){
                    diskonHarga.setText(String.valueOf(8));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Suzuki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(7));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Yamaha".equals(combo1)){
                    diskonHarga.setText(String.valueOf(6));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }else if("Kawasaki".equals(combo1)){
                    diskonHarga.setText(String.valueOf(5));
                    TextField2 = Integer.valueOf(hargaMotor.getText());
                    TextField3 = Integer.valueOf(diskonHarga.getText());
                    diskon = TextField2 /100 * TextField3;
                    result = TextField2 - diskon;
                    totalBayar.setText(String.valueOf(result));
                }
            } 
        }
        else {
            JOptionPane.showMessageDialog(this, "Piihan Bayar belum dipilih"); 
            diskonHarga.setText("");
            totalBayar.setText("");
        }
    }//GEN-LAST:event_hitungHargaActionPerformed

    private void motorSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motorSportActionPerformed
       String Val= PilihMerk.getSelectedItem().toString();
       
       if("Honda".equals(Val)){
            hargaMotor.setText(String.valueOf(32000000));
        }
        else if("Suzuki".equals(Val)){
            hargaMotor.setText(String.valueOf(33000000));
        }
        else if("Yamaha".equals(Val)){
              hargaMotor.setText(String.valueOf(30000000));
        }
         else if("Kawasaki".equals(Val)){
              hargaMotor.setText(String.valueOf(28000000));
        }  else {
             JOptionPane.showMessageDialog(this, "Merk Motor Belum di pilih");        
             hargaMotor.setText(String.valueOf(""));
        }
    }//GEN-LAST:event_motorSportActionPerformed

    private void hitungLagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungLagiActionPerformed
        NamaPembeli.setText("");
        hargaMotor.setText("");
        diskonHarga.setText("");
        totalBayar.setText("");
        buttonGroup1.clearSelection();
        PilihMerk.setSelectedIndex(0);
        jenisPembayaran.setSelectedIndex(0);

        
    }//GEN-LAST:event_hitungLagiActionPerformed

    private void keluarAppsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarAppsActionPerformed
       JFrame frame = new JFrame("Exit");
       if(JOptionPane.showConfirmDialog(frame, "Yakin keluar dari aplikasi ?","Exit",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
            {
                System.exit(0);
            }
    }//GEN-LAST:event_keluarAppsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanMotor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NamaPembeli;
    private javax.swing.JComboBox<String> PilihMerk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField diskonHarga;
    private javax.swing.JTextField hargaMotor;
    private javax.swing.JButton hitungHarga;
    private javax.swing.JButton hitungLagi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jenisPembayaran;
    private javax.swing.JButton keluarApps;
    private javax.swing.JRadioButton motorBebek;
    private javax.swing.JRadioButton motorMatic;
    private javax.swing.JRadioButton motorSport;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables
}
